// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: extractionService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ExtractionService service

func NewExtractionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ExtractionService service

type ExtractionService interface {
	Create(ctx context.Context, in *Extraction, opts ...client.CallOption) (*ExtractionResponse, error)
	Update(ctx context.Context, in *Extraction, opts ...client.CallOption) (*ExtractionResponse, error)
	Delete(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error)
	Get(ctx context.Context, in *Extraction, opts ...client.CallOption) (*ExtractionResponse, error)
	Search(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error)
	List(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error)
	// 获取距离用户最近的自提点
	NearestList(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error)
}

type extractionService struct {
	c    client.Client
	name string
}

func NewExtractionService(name string, c client.Client) ExtractionService {
	return &extractionService{
		c:    c,
		name: name,
	}
}

func (c *extractionService) Create(ctx context.Context, in *Extraction, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.Create", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionService) Update(ctx context.Context, in *Extraction, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.Update", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionService) Delete(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.Delete", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionService) Get(ctx context.Context, in *Extraction, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.Get", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionService) Search(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.Search", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionService) List(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.List", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionService) NearestList(ctx context.Context, in *ExtractionRequest, opts ...client.CallOption) (*ExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "ExtractionService.NearestList", in)
	out := new(ExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExtractionService service

type ExtractionServiceHandler interface {
	Create(context.Context, *Extraction, *ExtractionResponse) error
	Update(context.Context, *Extraction, *ExtractionResponse) error
	Delete(context.Context, *ExtractionRequest, *ExtractionResponse) error
	Get(context.Context, *Extraction, *ExtractionResponse) error
	Search(context.Context, *ExtractionRequest, *ExtractionResponse) error
	List(context.Context, *ExtractionRequest, *ExtractionResponse) error
	// 获取距离用户最近的自提点
	NearestList(context.Context, *ExtractionRequest, *ExtractionResponse) error
}

func RegisterExtractionServiceHandler(s server.Server, hdlr ExtractionServiceHandler, opts ...server.HandlerOption) error {
	type extractionService interface {
		Create(ctx context.Context, in *Extraction, out *ExtractionResponse) error
		Update(ctx context.Context, in *Extraction, out *ExtractionResponse) error
		Delete(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error
		Get(ctx context.Context, in *Extraction, out *ExtractionResponse) error
		Search(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error
		List(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error
		NearestList(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error
	}
	type ExtractionService struct {
		extractionService
	}
	h := &extractionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ExtractionService{h}, opts...))
}

type extractionServiceHandler struct {
	ExtractionServiceHandler
}

func (h *extractionServiceHandler) Create(ctx context.Context, in *Extraction, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.Create(ctx, in, out)
}

func (h *extractionServiceHandler) Update(ctx context.Context, in *Extraction, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.Update(ctx, in, out)
}

func (h *extractionServiceHandler) Delete(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.Delete(ctx, in, out)
}

func (h *extractionServiceHandler) Get(ctx context.Context, in *Extraction, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.Get(ctx, in, out)
}

func (h *extractionServiceHandler) Search(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.Search(ctx, in, out)
}

func (h *extractionServiceHandler) List(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.List(ctx, in, out)
}

func (h *extractionServiceHandler) NearestList(ctx context.Context, in *ExtractionRequest, out *ExtractionResponse) error {
	return h.ExtractionServiceHandler.NearestList(ctx, in, out)
}
