// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: expressService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ExpressService service

func NewExpressServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ExpressService service

type ExpressService interface {
	Create(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error)
	Update(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error)
	Delete(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error)
	Get(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error)
	Search(ctx context.Context, in *ExpressRequest, opts ...client.CallOption) (*ExpressResponse, error)
	List(ctx context.Context, in *ExpressRequest, opts ...client.CallOption) (*ExpressResponse, error)
}

type expressService struct {
	c    client.Client
	name string
}

func NewExpressService(name string, c client.Client) ExpressService {
	return &expressService{
		c:    c,
		name: name,
	}
}

func (c *expressService) Create(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error) {
	req := c.c.NewRequest(c.name, "ExpressService.Create", in)
	out := new(ExpressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expressService) Update(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error) {
	req := c.c.NewRequest(c.name, "ExpressService.Update", in)
	out := new(ExpressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expressService) Delete(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error) {
	req := c.c.NewRequest(c.name, "ExpressService.Delete", in)
	out := new(ExpressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expressService) Get(ctx context.Context, in *Express, opts ...client.CallOption) (*ExpressResponse, error) {
	req := c.c.NewRequest(c.name, "ExpressService.Get", in)
	out := new(ExpressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expressService) Search(ctx context.Context, in *ExpressRequest, opts ...client.CallOption) (*ExpressResponse, error) {
	req := c.c.NewRequest(c.name, "ExpressService.Search", in)
	out := new(ExpressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expressService) List(ctx context.Context, in *ExpressRequest, opts ...client.CallOption) (*ExpressResponse, error) {
	req := c.c.NewRequest(c.name, "ExpressService.List", in)
	out := new(ExpressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ExpressService service

type ExpressServiceHandler interface {
	Create(context.Context, *Express, *ExpressResponse) error
	Update(context.Context, *Express, *ExpressResponse) error
	Delete(context.Context, *Express, *ExpressResponse) error
	Get(context.Context, *Express, *ExpressResponse) error
	Search(context.Context, *ExpressRequest, *ExpressResponse) error
	List(context.Context, *ExpressRequest, *ExpressResponse) error
}

func RegisterExpressServiceHandler(s server.Server, hdlr ExpressServiceHandler, opts ...server.HandlerOption) error {
	type expressService interface {
		Create(ctx context.Context, in *Express, out *ExpressResponse) error
		Update(ctx context.Context, in *Express, out *ExpressResponse) error
		Delete(ctx context.Context, in *Express, out *ExpressResponse) error
		Get(ctx context.Context, in *Express, out *ExpressResponse) error
		Search(ctx context.Context, in *ExpressRequest, out *ExpressResponse) error
		List(ctx context.Context, in *ExpressRequest, out *ExpressResponse) error
	}
	type ExpressService struct {
		expressService
	}
	h := &expressServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ExpressService{h}, opts...))
}

type expressServiceHandler struct {
	ExpressServiceHandler
}

func (h *expressServiceHandler) Create(ctx context.Context, in *Express, out *ExpressResponse) error {
	return h.ExpressServiceHandler.Create(ctx, in, out)
}

func (h *expressServiceHandler) Update(ctx context.Context, in *Express, out *ExpressResponse) error {
	return h.ExpressServiceHandler.Update(ctx, in, out)
}

func (h *expressServiceHandler) Delete(ctx context.Context, in *Express, out *ExpressResponse) error {
	return h.ExpressServiceHandler.Delete(ctx, in, out)
}

func (h *expressServiceHandler) Get(ctx context.Context, in *Express, out *ExpressResponse) error {
	return h.ExpressServiceHandler.Get(ctx, in, out)
}

func (h *expressServiceHandler) Search(ctx context.Context, in *ExpressRequest, out *ExpressResponse) error {
	return h.ExpressServiceHandler.Search(ctx, in, out)
}

func (h *expressServiceHandler) List(ctx context.Context, in *ExpressRequest, out *ExpressResponse) error {
	return h.ExpressServiceHandler.List(ctx, in, out)
}
