// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: freightTemplateService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FreightTemplateService service

func NewFreightTemplateServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FreightTemplateService service

type FreightTemplateService interface {
	Create(ctx context.Context, in *FreightTemplate, opts ...client.CallOption) (*FreightTemplateResponse, error)
	Update(ctx context.Context, in *FreightTemplate, opts ...client.CallOption) (*FreightTemplateResponse, error)
	Copy(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error)
	Delete(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error)
	Search(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error)
	List(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error)
	Get(ctx context.Context, in *FreightTemplate, opts ...client.CallOption) (*FreightTemplateResponse, error)
	// 设置默认使用模板
	Defaulted(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error)
	// 获取默认使用的模板
	GetDefault(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error)
}

type freightTemplateService struct {
	c    client.Client
	name string
}

func NewFreightTemplateService(name string, c client.Client) FreightTemplateService {
	return &freightTemplateService{
		c:    c,
		name: name,
	}
}

func (c *freightTemplateService) Create(ctx context.Context, in *FreightTemplate, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Create", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) Update(ctx context.Context, in *FreightTemplate, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Update", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) Copy(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Copy", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) Delete(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Delete", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) Search(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Search", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) List(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.List", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) Get(ctx context.Context, in *FreightTemplate, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Get", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) Defaulted(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.Defaulted", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freightTemplateService) GetDefault(ctx context.Context, in *FreightTemplateRequest, opts ...client.CallOption) (*FreightTemplateResponse, error) {
	req := c.c.NewRequest(c.name, "FreightTemplateService.GetDefault", in)
	out := new(FreightTemplateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FreightTemplateService service

type FreightTemplateServiceHandler interface {
	Create(context.Context, *FreightTemplate, *FreightTemplateResponse) error
	Update(context.Context, *FreightTemplate, *FreightTemplateResponse) error
	Copy(context.Context, *FreightTemplateRequest, *FreightTemplateResponse) error
	Delete(context.Context, *FreightTemplateRequest, *FreightTemplateResponse) error
	Search(context.Context, *FreightTemplateRequest, *FreightTemplateResponse) error
	List(context.Context, *FreightTemplateRequest, *FreightTemplateResponse) error
	Get(context.Context, *FreightTemplate, *FreightTemplateResponse) error
	// 设置默认使用模板
	Defaulted(context.Context, *FreightTemplateRequest, *FreightTemplateResponse) error
	// 获取默认使用的模板
	GetDefault(context.Context, *FreightTemplateRequest, *FreightTemplateResponse) error
}

func RegisterFreightTemplateServiceHandler(s server.Server, hdlr FreightTemplateServiceHandler, opts ...server.HandlerOption) error {
	type freightTemplateService interface {
		Create(ctx context.Context, in *FreightTemplate, out *FreightTemplateResponse) error
		Update(ctx context.Context, in *FreightTemplate, out *FreightTemplateResponse) error
		Copy(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error
		Delete(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error
		Search(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error
		List(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error
		Get(ctx context.Context, in *FreightTemplate, out *FreightTemplateResponse) error
		Defaulted(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error
		GetDefault(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error
	}
	type FreightTemplateService struct {
		freightTemplateService
	}
	h := &freightTemplateServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FreightTemplateService{h}, opts...))
}

type freightTemplateServiceHandler struct {
	FreightTemplateServiceHandler
}

func (h *freightTemplateServiceHandler) Create(ctx context.Context, in *FreightTemplate, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Create(ctx, in, out)
}

func (h *freightTemplateServiceHandler) Update(ctx context.Context, in *FreightTemplate, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Update(ctx, in, out)
}

func (h *freightTemplateServiceHandler) Copy(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Copy(ctx, in, out)
}

func (h *freightTemplateServiceHandler) Delete(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Delete(ctx, in, out)
}

func (h *freightTemplateServiceHandler) Search(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Search(ctx, in, out)
}

func (h *freightTemplateServiceHandler) List(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.List(ctx, in, out)
}

func (h *freightTemplateServiceHandler) Get(ctx context.Context, in *FreightTemplate, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Get(ctx, in, out)
}

func (h *freightTemplateServiceHandler) Defaulted(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.Defaulted(ctx, in, out)
}

func (h *freightTemplateServiceHandler) GetDefault(ctx context.Context, in *FreightTemplateRequest, out *FreightTemplateResponse) error {
	return h.FreightTemplateServiceHandler.GetDefault(ctx, in, out)
}
