// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: integralCategoryService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for IntegralCategoryService service

func NewIntegralCategoryServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for IntegralCategoryService service

type IntegralCategoryService interface {
	Create(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error)
	Update(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error)
	Delete(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error)
	Get(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error)
	Tree(ctx context.Context, in *IntegralCategoryRequest, opts ...client.CallOption) (*IntegralCategoryResponse, error)
	List(ctx context.Context, in *IntegralCategoryRequest, opts ...client.CallOption) (*IntegralCategoryResponse, error)
	Search(ctx context.Context, in *IntegralCategoryRequest, opts ...client.CallOption) (*IntegralCategoryResponse, error)
}

type integralCategoryService struct {
	c    client.Client
	name string
}

func NewIntegralCategoryService(name string, c client.Client) IntegralCategoryService {
	return &integralCategoryService{
		c:    c,
		name: name,
	}
}

func (c *integralCategoryService) Create(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.Create", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralCategoryService) Update(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.Update", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralCategoryService) Delete(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.Delete", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralCategoryService) Get(ctx context.Context, in *IntegralCategory, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.Get", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralCategoryService) Tree(ctx context.Context, in *IntegralCategoryRequest, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.Tree", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralCategoryService) List(ctx context.Context, in *IntegralCategoryRequest, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.List", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralCategoryService) Search(ctx context.Context, in *IntegralCategoryRequest, opts ...client.CallOption) (*IntegralCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralCategoryService.Search", in)
	out := new(IntegralCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IntegralCategoryService service

type IntegralCategoryServiceHandler interface {
	Create(context.Context, *IntegralCategory, *IntegralCategoryResponse) error
	Update(context.Context, *IntegralCategory, *IntegralCategoryResponse) error
	Delete(context.Context, *IntegralCategory, *IntegralCategoryResponse) error
	Get(context.Context, *IntegralCategory, *IntegralCategoryResponse) error
	Tree(context.Context, *IntegralCategoryRequest, *IntegralCategoryResponse) error
	List(context.Context, *IntegralCategoryRequest, *IntegralCategoryResponse) error
	Search(context.Context, *IntegralCategoryRequest, *IntegralCategoryResponse) error
}

func RegisterIntegralCategoryServiceHandler(s server.Server, hdlr IntegralCategoryServiceHandler, opts ...server.HandlerOption) error {
	type integralCategoryService interface {
		Create(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error
		Update(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error
		Delete(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error
		Get(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error
		Tree(ctx context.Context, in *IntegralCategoryRequest, out *IntegralCategoryResponse) error
		List(ctx context.Context, in *IntegralCategoryRequest, out *IntegralCategoryResponse) error
		Search(ctx context.Context, in *IntegralCategoryRequest, out *IntegralCategoryResponse) error
	}
	type IntegralCategoryService struct {
		integralCategoryService
	}
	h := &integralCategoryServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&IntegralCategoryService{h}, opts...))
}

type integralCategoryServiceHandler struct {
	IntegralCategoryServiceHandler
}

func (h *integralCategoryServiceHandler) Create(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.Create(ctx, in, out)
}

func (h *integralCategoryServiceHandler) Update(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.Update(ctx, in, out)
}

func (h *integralCategoryServiceHandler) Delete(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.Delete(ctx, in, out)
}

func (h *integralCategoryServiceHandler) Get(ctx context.Context, in *IntegralCategory, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.Get(ctx, in, out)
}

func (h *integralCategoryServiceHandler) Tree(ctx context.Context, in *IntegralCategoryRequest, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.Tree(ctx, in, out)
}

func (h *integralCategoryServiceHandler) List(ctx context.Context, in *IntegralCategoryRequest, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.List(ctx, in, out)
}

func (h *integralCategoryServiceHandler) Search(ctx context.Context, in *IntegralCategoryRequest, out *IntegralCategoryResponse) error {
	return h.IntegralCategoryServiceHandler.Search(ctx, in, out)
}
