// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: integralExchangeLogService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for IntegralExchangeLogService service

func NewIntegralExchangeLogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for IntegralExchangeLogService service

type IntegralExchangeLogService interface {
	//物流信息详情
	Detail(ctx context.Context, in *IntegralExchangeLog, opts ...client.CallOption) (*IntegralExchangeLogResponse, error)
	//查询物流信息
	Search(ctx context.Context, in *IntegralExchangeLogRequest, opts ...client.CallOption) (*IntegralExchangeLogResponse, error)
}

type integralExchangeLogService struct {
	c    client.Client
	name string
}

func NewIntegralExchangeLogService(name string, c client.Client) IntegralExchangeLogService {
	return &integralExchangeLogService{
		c:    c,
		name: name,
	}
}

func (c *integralExchangeLogService) Detail(ctx context.Context, in *IntegralExchangeLog, opts ...client.CallOption) (*IntegralExchangeLogResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralExchangeLogService.Detail", in)
	out := new(IntegralExchangeLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integralExchangeLogService) Search(ctx context.Context, in *IntegralExchangeLogRequest, opts ...client.CallOption) (*IntegralExchangeLogResponse, error) {
	req := c.c.NewRequest(c.name, "IntegralExchangeLogService.Search", in)
	out := new(IntegralExchangeLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IntegralExchangeLogService service

type IntegralExchangeLogServiceHandler interface {
	//物流信息详情
	Detail(context.Context, *IntegralExchangeLog, *IntegralExchangeLogResponse) error
	//查询物流信息
	Search(context.Context, *IntegralExchangeLogRequest, *IntegralExchangeLogResponse) error
}

func RegisterIntegralExchangeLogServiceHandler(s server.Server, hdlr IntegralExchangeLogServiceHandler, opts ...server.HandlerOption) error {
	type integralExchangeLogService interface {
		Detail(ctx context.Context, in *IntegralExchangeLog, out *IntegralExchangeLogResponse) error
		Search(ctx context.Context, in *IntegralExchangeLogRequest, out *IntegralExchangeLogResponse) error
	}
	type IntegralExchangeLogService struct {
		integralExchangeLogService
	}
	h := &integralExchangeLogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&IntegralExchangeLogService{h}, opts...))
}

type integralExchangeLogServiceHandler struct {
	IntegralExchangeLogServiceHandler
}

func (h *integralExchangeLogServiceHandler) Detail(ctx context.Context, in *IntegralExchangeLog, out *IntegralExchangeLogResponse) error {
	return h.IntegralExchangeLogServiceHandler.Detail(ctx, in, out)
}

func (h *integralExchangeLogServiceHandler) Search(ctx context.Context, in *IntegralExchangeLogRequest, out *IntegralExchangeLogResponse) error {
	return h.IntegralExchangeLogServiceHandler.Search(ctx, in, out)
}
