// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: goodsService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GoodsService service

func NewGoodsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GoodsService service

type GoodsService interface {
	//分销商品添加
	Create(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error)
	//分销商品修改
	Update(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error)
	//分销商品移除
	Delete(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error)
	//分销商品详情
	Detail(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error)
	//分销商品查询
	Search(ctx context.Context, in *GoodsRequest, opts ...client.CallOption) (*GoodsResponse, error)
	//分销商品取消/参与推广
	Switch(ctx context.Context, in *GoodsRequest, opts ...client.CallOption) (*GoodsResponse, error)
	//产品搜索
	ProductSearch(ctx context.Context, in *GoodsRequest, opts ...client.CallOption) (*GoodsResponse, error)
}

type goodsService struct {
	c    client.Client
	name string
}

func NewGoodsService(name string, c client.Client) GoodsService {
	return &goodsService{
		c:    c,
		name: name,
	}
}

func (c *goodsService) Create(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.Create", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) Update(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.Update", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) Delete(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.Delete", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) Detail(ctx context.Context, in *Goods, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.Detail", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) Search(ctx context.Context, in *GoodsRequest, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.Search", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) Switch(ctx context.Context, in *GoodsRequest, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.Switch", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) ProductSearch(ctx context.Context, in *GoodsRequest, opts ...client.CallOption) (*GoodsResponse, error) {
	req := c.c.NewRequest(c.name, "GoodsService.ProductSearch", in)
	out := new(GoodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoodsService service

type GoodsServiceHandler interface {
	//分销商品添加
	Create(context.Context, *Goods, *GoodsResponse) error
	//分销商品修改
	Update(context.Context, *Goods, *GoodsResponse) error
	//分销商品移除
	Delete(context.Context, *Goods, *GoodsResponse) error
	//分销商品详情
	Detail(context.Context, *Goods, *GoodsResponse) error
	//分销商品查询
	Search(context.Context, *GoodsRequest, *GoodsResponse) error
	//分销商品取消/参与推广
	Switch(context.Context, *GoodsRequest, *GoodsResponse) error
	//产品搜索
	ProductSearch(context.Context, *GoodsRequest, *GoodsResponse) error
}

func RegisterGoodsServiceHandler(s server.Server, hdlr GoodsServiceHandler, opts ...server.HandlerOption) error {
	type goodsService interface {
		Create(ctx context.Context, in *Goods, out *GoodsResponse) error
		Update(ctx context.Context, in *Goods, out *GoodsResponse) error
		Delete(ctx context.Context, in *Goods, out *GoodsResponse) error
		Detail(ctx context.Context, in *Goods, out *GoodsResponse) error
		Search(ctx context.Context, in *GoodsRequest, out *GoodsResponse) error
		Switch(ctx context.Context, in *GoodsRequest, out *GoodsResponse) error
		ProductSearch(ctx context.Context, in *GoodsRequest, out *GoodsResponse) error
	}
	type GoodsService struct {
		goodsService
	}
	h := &goodsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GoodsService{h}, opts...))
}

type goodsServiceHandler struct {
	GoodsServiceHandler
}

func (h *goodsServiceHandler) Create(ctx context.Context, in *Goods, out *GoodsResponse) error {
	return h.GoodsServiceHandler.Create(ctx, in, out)
}

func (h *goodsServiceHandler) Update(ctx context.Context, in *Goods, out *GoodsResponse) error {
	return h.GoodsServiceHandler.Update(ctx, in, out)
}

func (h *goodsServiceHandler) Delete(ctx context.Context, in *Goods, out *GoodsResponse) error {
	return h.GoodsServiceHandler.Delete(ctx, in, out)
}

func (h *goodsServiceHandler) Detail(ctx context.Context, in *Goods, out *GoodsResponse) error {
	return h.GoodsServiceHandler.Detail(ctx, in, out)
}

func (h *goodsServiceHandler) Search(ctx context.Context, in *GoodsRequest, out *GoodsResponse) error {
	return h.GoodsServiceHandler.Search(ctx, in, out)
}

func (h *goodsServiceHandler) Switch(ctx context.Context, in *GoodsRequest, out *GoodsResponse) error {
	return h.GoodsServiceHandler.Switch(ctx, in, out)
}

func (h *goodsServiceHandler) ProductSearch(ctx context.Context, in *GoodsRequest, out *GoodsResponse) error {
	return h.GoodsServiceHandler.ProductSearch(ctx, in, out)
}
