// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cashCollectService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CashCollectService service

func NewCashCollectServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CashCollectService service

type CashCollectService interface {
	Create(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error)
	Update(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error)
	Delete(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error)
	Get(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error)
	List(ctx context.Context, in *CashCollectRequest, opts ...client.CallOption) (*CashCollectResponse, error)
	Search(ctx context.Context, in *CashCollectRequest, opts ...client.CallOption) (*CashCollectResponse, error)
}

type cashCollectService struct {
	c    client.Client
	name string
}

func NewCashCollectService(name string, c client.Client) CashCollectService {
	return &cashCollectService{
		c:    c,
		name: name,
	}
}

func (c *cashCollectService) Create(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error) {
	req := c.c.NewRequest(c.name, "CashCollectService.Create", in)
	out := new(CashCollectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashCollectService) Update(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error) {
	req := c.c.NewRequest(c.name, "CashCollectService.Update", in)
	out := new(CashCollectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashCollectService) Delete(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error) {
	req := c.c.NewRequest(c.name, "CashCollectService.Delete", in)
	out := new(CashCollectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashCollectService) Get(ctx context.Context, in *CashCollect, opts ...client.CallOption) (*CashCollectResponse, error) {
	req := c.c.NewRequest(c.name, "CashCollectService.Get", in)
	out := new(CashCollectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashCollectService) List(ctx context.Context, in *CashCollectRequest, opts ...client.CallOption) (*CashCollectResponse, error) {
	req := c.c.NewRequest(c.name, "CashCollectService.List", in)
	out := new(CashCollectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cashCollectService) Search(ctx context.Context, in *CashCollectRequest, opts ...client.CallOption) (*CashCollectResponse, error) {
	req := c.c.NewRequest(c.name, "CashCollectService.Search", in)
	out := new(CashCollectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CashCollectService service

type CashCollectServiceHandler interface {
	Create(context.Context, *CashCollect, *CashCollectResponse) error
	Update(context.Context, *CashCollect, *CashCollectResponse) error
	Delete(context.Context, *CashCollect, *CashCollectResponse) error
	Get(context.Context, *CashCollect, *CashCollectResponse) error
	List(context.Context, *CashCollectRequest, *CashCollectResponse) error
	Search(context.Context, *CashCollectRequest, *CashCollectResponse) error
}

func RegisterCashCollectServiceHandler(s server.Server, hdlr CashCollectServiceHandler, opts ...server.HandlerOption) error {
	type cashCollectService interface {
		Create(ctx context.Context, in *CashCollect, out *CashCollectResponse) error
		Update(ctx context.Context, in *CashCollect, out *CashCollectResponse) error
		Delete(ctx context.Context, in *CashCollect, out *CashCollectResponse) error
		Get(ctx context.Context, in *CashCollect, out *CashCollectResponse) error
		List(ctx context.Context, in *CashCollectRequest, out *CashCollectResponse) error
		Search(ctx context.Context, in *CashCollectRequest, out *CashCollectResponse) error
	}
	type CashCollectService struct {
		cashCollectService
	}
	h := &cashCollectServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CashCollectService{h}, opts...))
}

type cashCollectServiceHandler struct {
	CashCollectServiceHandler
}

func (h *cashCollectServiceHandler) Create(ctx context.Context, in *CashCollect, out *CashCollectResponse) error {
	return h.CashCollectServiceHandler.Create(ctx, in, out)
}

func (h *cashCollectServiceHandler) Update(ctx context.Context, in *CashCollect, out *CashCollectResponse) error {
	return h.CashCollectServiceHandler.Update(ctx, in, out)
}

func (h *cashCollectServiceHandler) Delete(ctx context.Context, in *CashCollect, out *CashCollectResponse) error {
	return h.CashCollectServiceHandler.Delete(ctx, in, out)
}

func (h *cashCollectServiceHandler) Get(ctx context.Context, in *CashCollect, out *CashCollectResponse) error {
	return h.CashCollectServiceHandler.Get(ctx, in, out)
}

func (h *cashCollectServiceHandler) List(ctx context.Context, in *CashCollectRequest, out *CashCollectResponse) error {
	return h.CashCollectServiceHandler.List(ctx, in, out)
}

func (h *cashCollectServiceHandler) Search(ctx context.Context, in *CashCollectRequest, out *CashCollectResponse) error {
	return h.CashCollectServiceHandler.Search(ctx, in, out)
}
