// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: orderAllotAddressService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrderAllotAddressService service

func NewOrderAllotAddressServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrderAllotAddressService service

type OrderAllotAddressService interface {
	Create(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error)
	Update(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error)
	Delete(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error)
	Get(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error)
	List(ctx context.Context, in *OrderAllotAddressRequest, opts ...client.CallOption) (*OrderAllotAddressResponse, error)
	Search(ctx context.Context, in *OrderAllotAddressRequest, opts ...client.CallOption) (*OrderAllotAddressResponse, error)
}

type orderAllotAddressService struct {
	c    client.Client
	name string
}

func NewOrderAllotAddressService(name string, c client.Client) OrderAllotAddressService {
	return &orderAllotAddressService{
		c:    c,
		name: name,
	}
}

func (c *orderAllotAddressService) Create(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error) {
	req := c.c.NewRequest(c.name, "OrderAllotAddressService.Create", in)
	out := new(OrderAllotAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderAllotAddressService) Update(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error) {
	req := c.c.NewRequest(c.name, "OrderAllotAddressService.Update", in)
	out := new(OrderAllotAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderAllotAddressService) Delete(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error) {
	req := c.c.NewRequest(c.name, "OrderAllotAddressService.Delete", in)
	out := new(OrderAllotAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderAllotAddressService) Get(ctx context.Context, in *OrderAllotAddress, opts ...client.CallOption) (*OrderAllotAddressResponse, error) {
	req := c.c.NewRequest(c.name, "OrderAllotAddressService.Get", in)
	out := new(OrderAllotAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderAllotAddressService) List(ctx context.Context, in *OrderAllotAddressRequest, opts ...client.CallOption) (*OrderAllotAddressResponse, error) {
	req := c.c.NewRequest(c.name, "OrderAllotAddressService.List", in)
	out := new(OrderAllotAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderAllotAddressService) Search(ctx context.Context, in *OrderAllotAddressRequest, opts ...client.CallOption) (*OrderAllotAddressResponse, error) {
	req := c.c.NewRequest(c.name, "OrderAllotAddressService.Search", in)
	out := new(OrderAllotAddressResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderAllotAddressService service

type OrderAllotAddressServiceHandler interface {
	Create(context.Context, *OrderAllotAddress, *OrderAllotAddressResponse) error
	Update(context.Context, *OrderAllotAddress, *OrderAllotAddressResponse) error
	Delete(context.Context, *OrderAllotAddress, *OrderAllotAddressResponse) error
	Get(context.Context, *OrderAllotAddress, *OrderAllotAddressResponse) error
	List(context.Context, *OrderAllotAddressRequest, *OrderAllotAddressResponse) error
	Search(context.Context, *OrderAllotAddressRequest, *OrderAllotAddressResponse) error
}

func RegisterOrderAllotAddressServiceHandler(s server.Server, hdlr OrderAllotAddressServiceHandler, opts ...server.HandlerOption) error {
	type orderAllotAddressService interface {
		Create(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error
		Update(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error
		Delete(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error
		Get(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error
		List(ctx context.Context, in *OrderAllotAddressRequest, out *OrderAllotAddressResponse) error
		Search(ctx context.Context, in *OrderAllotAddressRequest, out *OrderAllotAddressResponse) error
	}
	type OrderAllotAddressService struct {
		orderAllotAddressService
	}
	h := &orderAllotAddressServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderAllotAddressService{h}, opts...))
}

type orderAllotAddressServiceHandler struct {
	OrderAllotAddressServiceHandler
}

func (h *orderAllotAddressServiceHandler) Create(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error {
	return h.OrderAllotAddressServiceHandler.Create(ctx, in, out)
}

func (h *orderAllotAddressServiceHandler) Update(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error {
	return h.OrderAllotAddressServiceHandler.Update(ctx, in, out)
}

func (h *orderAllotAddressServiceHandler) Delete(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error {
	return h.OrderAllotAddressServiceHandler.Delete(ctx, in, out)
}

func (h *orderAllotAddressServiceHandler) Get(ctx context.Context, in *OrderAllotAddress, out *OrderAllotAddressResponse) error {
	return h.OrderAllotAddressServiceHandler.Get(ctx, in, out)
}

func (h *orderAllotAddressServiceHandler) List(ctx context.Context, in *OrderAllotAddressRequest, out *OrderAllotAddressResponse) error {
	return h.OrderAllotAddressServiceHandler.List(ctx, in, out)
}

func (h *orderAllotAddressServiceHandler) Search(ctx context.Context, in *OrderAllotAddressRequest, out *OrderAllotAddressResponse) error {
	return h.OrderAllotAddressServiceHandler.Search(ctx, in, out)
}
