// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: orderProfitService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrderProfitService service

func NewOrderProfitServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrderProfitService service

type OrderProfitService interface {
	Detail(ctx context.Context, in *OrderProfit, opts ...client.CallOption) (*OrderProfitResponse, error)
	Search(ctx context.Context, in *OrderProfitRequest, opts ...client.CallOption) (*OrderProfitResponse, error)
}

type orderProfitService struct {
	c    client.Client
	name string
}

func NewOrderProfitService(name string, c client.Client) OrderProfitService {
	return &orderProfitService{
		c:    c,
		name: name,
	}
}

func (c *orderProfitService) Detail(ctx context.Context, in *OrderProfit, opts ...client.CallOption) (*OrderProfitResponse, error) {
	req := c.c.NewRequest(c.name, "OrderProfitService.Detail", in)
	out := new(OrderProfitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderProfitService) Search(ctx context.Context, in *OrderProfitRequest, opts ...client.CallOption) (*OrderProfitResponse, error) {
	req := c.c.NewRequest(c.name, "OrderProfitService.Search", in)
	out := new(OrderProfitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderProfitService service

type OrderProfitServiceHandler interface {
	Detail(context.Context, *OrderProfit, *OrderProfitResponse) error
	Search(context.Context, *OrderProfitRequest, *OrderProfitResponse) error
}

func RegisterOrderProfitServiceHandler(s server.Server, hdlr OrderProfitServiceHandler, opts ...server.HandlerOption) error {
	type orderProfitService interface {
		Detail(ctx context.Context, in *OrderProfit, out *OrderProfitResponse) error
		Search(ctx context.Context, in *OrderProfitRequest, out *OrderProfitResponse) error
	}
	type OrderProfitService struct {
		orderProfitService
	}
	h := &orderProfitServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderProfitService{h}, opts...))
}

type orderProfitServiceHandler struct {
	OrderProfitServiceHandler
}

func (h *orderProfitServiceHandler) Detail(ctx context.Context, in *OrderProfit, out *OrderProfitResponse) error {
	return h.OrderProfitServiceHandler.Detail(ctx, in, out)
}

func (h *orderProfitServiceHandler) Search(ctx context.Context, in *OrderProfitRequest, out *OrderProfitResponse) error {
	return h.OrderProfitServiceHandler.Search(ctx, in, out)
}
