// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: realstoreService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RealstoreService service

func NewRealstoreServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RealstoreService service

type RealstoreService interface {
	Create(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error)
	Update(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error)
	Delete(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error)
	Detail(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error)
	List(ctx context.Context, in *RealstoreRequest, opts ...client.CallOption) (*RealstoreResponse, error)
	Search(ctx context.Context, in *RealstoreRequest, opts ...client.CallOption) (*RealstoreResponse, error)
}

type realstoreService struct {
	c    client.Client
	name string
}

func NewRealstoreService(name string, c client.Client) RealstoreService {
	return &realstoreService{
		c:    c,
		name: name,
	}
}

func (c *realstoreService) Create(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error) {
	req := c.c.NewRequest(c.name, "RealstoreService.Create", in)
	out := new(RealstoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realstoreService) Update(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error) {
	req := c.c.NewRequest(c.name, "RealstoreService.Update", in)
	out := new(RealstoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realstoreService) Delete(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error) {
	req := c.c.NewRequest(c.name, "RealstoreService.Delete", in)
	out := new(RealstoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realstoreService) Detail(ctx context.Context, in *Realstore, opts ...client.CallOption) (*RealstoreResponse, error) {
	req := c.c.NewRequest(c.name, "RealstoreService.Detail", in)
	out := new(RealstoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realstoreService) List(ctx context.Context, in *RealstoreRequest, opts ...client.CallOption) (*RealstoreResponse, error) {
	req := c.c.NewRequest(c.name, "RealstoreService.List", in)
	out := new(RealstoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realstoreService) Search(ctx context.Context, in *RealstoreRequest, opts ...client.CallOption) (*RealstoreResponse, error) {
	req := c.c.NewRequest(c.name, "RealstoreService.Search", in)
	out := new(RealstoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RealstoreService service

type RealstoreServiceHandler interface {
	Create(context.Context, *Realstore, *RealstoreResponse) error
	Update(context.Context, *Realstore, *RealstoreResponse) error
	Delete(context.Context, *Realstore, *RealstoreResponse) error
	Detail(context.Context, *Realstore, *RealstoreResponse) error
	List(context.Context, *RealstoreRequest, *RealstoreResponse) error
	Search(context.Context, *RealstoreRequest, *RealstoreResponse) error
}

func RegisterRealstoreServiceHandler(s server.Server, hdlr RealstoreServiceHandler, opts ...server.HandlerOption) error {
	type realstoreService interface {
		Create(ctx context.Context, in *Realstore, out *RealstoreResponse) error
		Update(ctx context.Context, in *Realstore, out *RealstoreResponse) error
		Delete(ctx context.Context, in *Realstore, out *RealstoreResponse) error
		Detail(ctx context.Context, in *Realstore, out *RealstoreResponse) error
		List(ctx context.Context, in *RealstoreRequest, out *RealstoreResponse) error
		Search(ctx context.Context, in *RealstoreRequest, out *RealstoreResponse) error
	}
	type RealstoreService struct {
		realstoreService
	}
	h := &realstoreServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RealstoreService{h}, opts...))
}

type realstoreServiceHandler struct {
	RealstoreServiceHandler
}

func (h *realstoreServiceHandler) Create(ctx context.Context, in *Realstore, out *RealstoreResponse) error {
	return h.RealstoreServiceHandler.Create(ctx, in, out)
}

func (h *realstoreServiceHandler) Update(ctx context.Context, in *Realstore, out *RealstoreResponse) error {
	return h.RealstoreServiceHandler.Update(ctx, in, out)
}

func (h *realstoreServiceHandler) Delete(ctx context.Context, in *Realstore, out *RealstoreResponse) error {
	return h.RealstoreServiceHandler.Delete(ctx, in, out)
}

func (h *realstoreServiceHandler) Detail(ctx context.Context, in *Realstore, out *RealstoreResponse) error {
	return h.RealstoreServiceHandler.Detail(ctx, in, out)
}

func (h *realstoreServiceHandler) List(ctx context.Context, in *RealstoreRequest, out *RealstoreResponse) error {
	return h.RealstoreServiceHandler.List(ctx, in, out)
}

func (h *realstoreServiceHandler) Search(ctx context.Context, in *RealstoreRequest, out *RealstoreResponse) error {
	return h.RealstoreServiceHandler.Search(ctx, in, out)
}
