// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: sliderService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SliderService service

func NewSliderServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SliderService service

type SliderService interface {
	Create(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error)
	Update(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error)
	Delete(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error)
	Get(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error)
	List(ctx context.Context, in *SliderRequest, opts ...client.CallOption) (*SliderResponse, error)
	Search(ctx context.Context, in *SliderRequest, opts ...client.CallOption) (*SliderResponse, error)
}

type sliderService struct {
	c    client.Client
	name string
}

func NewSliderService(name string, c client.Client) SliderService {
	return &sliderService{
		c:    c,
		name: name,
	}
}

func (c *sliderService) Create(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error) {
	req := c.c.NewRequest(c.name, "SliderService.Create", in)
	out := new(SliderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliderService) Update(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error) {
	req := c.c.NewRequest(c.name, "SliderService.Update", in)
	out := new(SliderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliderService) Delete(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error) {
	req := c.c.NewRequest(c.name, "SliderService.Delete", in)
	out := new(SliderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliderService) Get(ctx context.Context, in *Slider, opts ...client.CallOption) (*SliderResponse, error) {
	req := c.c.NewRequest(c.name, "SliderService.Get", in)
	out := new(SliderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliderService) List(ctx context.Context, in *SliderRequest, opts ...client.CallOption) (*SliderResponse, error) {
	req := c.c.NewRequest(c.name, "SliderService.List", in)
	out := new(SliderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliderService) Search(ctx context.Context, in *SliderRequest, opts ...client.CallOption) (*SliderResponse, error) {
	req := c.c.NewRequest(c.name, "SliderService.Search", in)
	out := new(SliderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SliderService service

type SliderServiceHandler interface {
	Create(context.Context, *Slider, *SliderResponse) error
	Update(context.Context, *Slider, *SliderResponse) error
	Delete(context.Context, *Slider, *SliderResponse) error
	Get(context.Context, *Slider, *SliderResponse) error
	List(context.Context, *SliderRequest, *SliderResponse) error
	Search(context.Context, *SliderRequest, *SliderResponse) error
}

func RegisterSliderServiceHandler(s server.Server, hdlr SliderServiceHandler, opts ...server.HandlerOption) error {
	type sliderService interface {
		Create(ctx context.Context, in *Slider, out *SliderResponse) error
		Update(ctx context.Context, in *Slider, out *SliderResponse) error
		Delete(ctx context.Context, in *Slider, out *SliderResponse) error
		Get(ctx context.Context, in *Slider, out *SliderResponse) error
		List(ctx context.Context, in *SliderRequest, out *SliderResponse) error
		Search(ctx context.Context, in *SliderRequest, out *SliderResponse) error
	}
	type SliderService struct {
		sliderService
	}
	h := &sliderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SliderService{h}, opts...))
}

type sliderServiceHandler struct {
	SliderServiceHandler
}

func (h *sliderServiceHandler) Create(ctx context.Context, in *Slider, out *SliderResponse) error {
	return h.SliderServiceHandler.Create(ctx, in, out)
}

func (h *sliderServiceHandler) Update(ctx context.Context, in *Slider, out *SliderResponse) error {
	return h.SliderServiceHandler.Update(ctx, in, out)
}

func (h *sliderServiceHandler) Delete(ctx context.Context, in *Slider, out *SliderResponse) error {
	return h.SliderServiceHandler.Delete(ctx, in, out)
}

func (h *sliderServiceHandler) Get(ctx context.Context, in *Slider, out *SliderResponse) error {
	return h.SliderServiceHandler.Get(ctx, in, out)
}

func (h *sliderServiceHandler) List(ctx context.Context, in *SliderRequest, out *SliderResponse) error {
	return h.SliderServiceHandler.List(ctx, in, out)
}

func (h *sliderServiceHandler) Search(ctx context.Context, in *SliderRequest, out *SliderResponse) error {
	return h.SliderServiceHandler.Search(ctx, in, out)
}
