// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: staffService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StaffService service

func NewStaffServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StaffService service

type StaffService interface {
	Create(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error)
	Update(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error)
	Delete(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error)
	Get(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error)
	List(ctx context.Context, in *StaffRequest, opts ...client.CallOption) (*StaffResponse, error)
	Search(ctx context.Context, in *StaffRequest, opts ...client.CallOption) (*StaffResponse, error)
}

type staffService struct {
	c    client.Client
	name string
}

func NewStaffService(name string, c client.Client) StaffService {
	return &staffService{
		c:    c,
		name: name,
	}
}

func (c *staffService) Create(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error) {
	req := c.c.NewRequest(c.name, "StaffService.Create", in)
	out := new(StaffResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) Update(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error) {
	req := c.c.NewRequest(c.name, "StaffService.Update", in)
	out := new(StaffResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) Delete(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error) {
	req := c.c.NewRequest(c.name, "StaffService.Delete", in)
	out := new(StaffResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) Get(ctx context.Context, in *Staff, opts ...client.CallOption) (*StaffResponse, error) {
	req := c.c.NewRequest(c.name, "StaffService.Get", in)
	out := new(StaffResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) List(ctx context.Context, in *StaffRequest, opts ...client.CallOption) (*StaffResponse, error) {
	req := c.c.NewRequest(c.name, "StaffService.List", in)
	out := new(StaffResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) Search(ctx context.Context, in *StaffRequest, opts ...client.CallOption) (*StaffResponse, error) {
	req := c.c.NewRequest(c.name, "StaffService.Search", in)
	out := new(StaffResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StaffService service

type StaffServiceHandler interface {
	Create(context.Context, *Staff, *StaffResponse) error
	Update(context.Context, *Staff, *StaffResponse) error
	Delete(context.Context, *Staff, *StaffResponse) error
	Get(context.Context, *Staff, *StaffResponse) error
	List(context.Context, *StaffRequest, *StaffResponse) error
	Search(context.Context, *StaffRequest, *StaffResponse) error
}

func RegisterStaffServiceHandler(s server.Server, hdlr StaffServiceHandler, opts ...server.HandlerOption) error {
	type staffService interface {
		Create(ctx context.Context, in *Staff, out *StaffResponse) error
		Update(ctx context.Context, in *Staff, out *StaffResponse) error
		Delete(ctx context.Context, in *Staff, out *StaffResponse) error
		Get(ctx context.Context, in *Staff, out *StaffResponse) error
		List(ctx context.Context, in *StaffRequest, out *StaffResponse) error
		Search(ctx context.Context, in *StaffRequest, out *StaffResponse) error
	}
	type StaffService struct {
		staffService
	}
	h := &staffServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StaffService{h}, opts...))
}

type staffServiceHandler struct {
	StaffServiceHandler
}

func (h *staffServiceHandler) Create(ctx context.Context, in *Staff, out *StaffResponse) error {
	return h.StaffServiceHandler.Create(ctx, in, out)
}

func (h *staffServiceHandler) Update(ctx context.Context, in *Staff, out *StaffResponse) error {
	return h.StaffServiceHandler.Update(ctx, in, out)
}

func (h *staffServiceHandler) Delete(ctx context.Context, in *Staff, out *StaffResponse) error {
	return h.StaffServiceHandler.Delete(ctx, in, out)
}

func (h *staffServiceHandler) Get(ctx context.Context, in *Staff, out *StaffResponse) error {
	return h.StaffServiceHandler.Get(ctx, in, out)
}

func (h *staffServiceHandler) List(ctx context.Context, in *StaffRequest, out *StaffResponse) error {
	return h.StaffServiceHandler.List(ctx, in, out)
}

func (h *staffServiceHandler) Search(ctx context.Context, in *StaffRequest, out *StaffResponse) error {
	return h.StaffServiceHandler.Search(ctx, in, out)
}
