// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: staffDutyLogService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StaffDutyLogService service

func NewStaffDutyLogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StaffDutyLogService service

type StaffDutyLogService interface {
	Create(ctx context.Context, in *StaffDutyLog, opts ...client.CallOption) (*StaffDutyLogResponse, error)
	Delete(ctx context.Context, in *StaffDutyLog, opts ...client.CallOption) (*StaffDutyLogResponse, error)
	Detail(ctx context.Context, in *StaffDutyLog, opts ...client.CallOption) (*StaffDutyLogResponse, error)
	Search(ctx context.Context, in *StaffDutyLogRequest, opts ...client.CallOption) (*StaffDutyLogResponse, error)
}

type staffDutyLogService struct {
	c    client.Client
	name string
}

func NewStaffDutyLogService(name string, c client.Client) StaffDutyLogService {
	return &staffDutyLogService{
		c:    c,
		name: name,
	}
}

func (c *staffDutyLogService) Create(ctx context.Context, in *StaffDutyLog, opts ...client.CallOption) (*StaffDutyLogResponse, error) {
	req := c.c.NewRequest(c.name, "StaffDutyLogService.Create", in)
	out := new(StaffDutyLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffDutyLogService) Delete(ctx context.Context, in *StaffDutyLog, opts ...client.CallOption) (*StaffDutyLogResponse, error) {
	req := c.c.NewRequest(c.name, "StaffDutyLogService.Delete", in)
	out := new(StaffDutyLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffDutyLogService) Detail(ctx context.Context, in *StaffDutyLog, opts ...client.CallOption) (*StaffDutyLogResponse, error) {
	req := c.c.NewRequest(c.name, "StaffDutyLogService.Detail", in)
	out := new(StaffDutyLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffDutyLogService) Search(ctx context.Context, in *StaffDutyLogRequest, opts ...client.CallOption) (*StaffDutyLogResponse, error) {
	req := c.c.NewRequest(c.name, "StaffDutyLogService.Search", in)
	out := new(StaffDutyLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StaffDutyLogService service

type StaffDutyLogServiceHandler interface {
	Create(context.Context, *StaffDutyLog, *StaffDutyLogResponse) error
	Delete(context.Context, *StaffDutyLog, *StaffDutyLogResponse) error
	Detail(context.Context, *StaffDutyLog, *StaffDutyLogResponse) error
	Search(context.Context, *StaffDutyLogRequest, *StaffDutyLogResponse) error
}

func RegisterStaffDutyLogServiceHandler(s server.Server, hdlr StaffDutyLogServiceHandler, opts ...server.HandlerOption) error {
	type staffDutyLogService interface {
		Create(ctx context.Context, in *StaffDutyLog, out *StaffDutyLogResponse) error
		Delete(ctx context.Context, in *StaffDutyLog, out *StaffDutyLogResponse) error
		Detail(ctx context.Context, in *StaffDutyLog, out *StaffDutyLogResponse) error
		Search(ctx context.Context, in *StaffDutyLogRequest, out *StaffDutyLogResponse) error
	}
	type StaffDutyLogService struct {
		staffDutyLogService
	}
	h := &staffDutyLogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StaffDutyLogService{h}, opts...))
}

type staffDutyLogServiceHandler struct {
	StaffDutyLogServiceHandler
}

func (h *staffDutyLogServiceHandler) Create(ctx context.Context, in *StaffDutyLog, out *StaffDutyLogResponse) error {
	return h.StaffDutyLogServiceHandler.Create(ctx, in, out)
}

func (h *staffDutyLogServiceHandler) Delete(ctx context.Context, in *StaffDutyLog, out *StaffDutyLogResponse) error {
	return h.StaffDutyLogServiceHandler.Delete(ctx, in, out)
}

func (h *staffDutyLogServiceHandler) Detail(ctx context.Context, in *StaffDutyLog, out *StaffDutyLogResponse) error {
	return h.StaffDutyLogServiceHandler.Detail(ctx, in, out)
}

func (h *staffDutyLogServiceHandler) Search(ctx context.Context, in *StaffDutyLogRequest, out *StaffDutyLogResponse) error {
	return h.StaffDutyLogServiceHandler.Search(ctx, in, out)
}
