// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: walletRechargeLogService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for WalletRechargeLogService service

func NewWalletRechargeLogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for WalletRechargeLogService service

type WalletRechargeLogService interface {
	Create(ctx context.Context, in *WalletRechargeLog, opts ...client.CallOption) (*WalletRechargeLogResponse, error)
	Delete(ctx context.Context, in *WalletRechargeLog, opts ...client.CallOption) (*WalletRechargeLogResponse, error)
	Detail(ctx context.Context, in *WalletRechargeLog, opts ...client.CallOption) (*WalletRechargeLogResponse, error)
	Search(ctx context.Context, in *WalletRechargeLogRequest, opts ...client.CallOption) (*WalletRechargeLogResponse, error)
}

type walletRechargeLogService struct {
	c    client.Client
	name string
}

func NewWalletRechargeLogService(name string, c client.Client) WalletRechargeLogService {
	return &walletRechargeLogService{
		c:    c,
		name: name,
	}
}

func (c *walletRechargeLogService) Create(ctx context.Context, in *WalletRechargeLog, opts ...client.CallOption) (*WalletRechargeLogResponse, error) {
	req := c.c.NewRequest(c.name, "WalletRechargeLogService.Create", in)
	out := new(WalletRechargeLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRechargeLogService) Delete(ctx context.Context, in *WalletRechargeLog, opts ...client.CallOption) (*WalletRechargeLogResponse, error) {
	req := c.c.NewRequest(c.name, "WalletRechargeLogService.Delete", in)
	out := new(WalletRechargeLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRechargeLogService) Detail(ctx context.Context, in *WalletRechargeLog, opts ...client.CallOption) (*WalletRechargeLogResponse, error) {
	req := c.c.NewRequest(c.name, "WalletRechargeLogService.Detail", in)
	out := new(WalletRechargeLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRechargeLogService) Search(ctx context.Context, in *WalletRechargeLogRequest, opts ...client.CallOption) (*WalletRechargeLogResponse, error) {
	req := c.c.NewRequest(c.name, "WalletRechargeLogService.Search", in)
	out := new(WalletRechargeLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletRechargeLogService service

type WalletRechargeLogServiceHandler interface {
	Create(context.Context, *WalletRechargeLog, *WalletRechargeLogResponse) error
	Delete(context.Context, *WalletRechargeLog, *WalletRechargeLogResponse) error
	Detail(context.Context, *WalletRechargeLog, *WalletRechargeLogResponse) error
	Search(context.Context, *WalletRechargeLogRequest, *WalletRechargeLogResponse) error
}

func RegisterWalletRechargeLogServiceHandler(s server.Server, hdlr WalletRechargeLogServiceHandler, opts ...server.HandlerOption) error {
	type walletRechargeLogService interface {
		Create(ctx context.Context, in *WalletRechargeLog, out *WalletRechargeLogResponse) error
		Delete(ctx context.Context, in *WalletRechargeLog, out *WalletRechargeLogResponse) error
		Detail(ctx context.Context, in *WalletRechargeLog, out *WalletRechargeLogResponse) error
		Search(ctx context.Context, in *WalletRechargeLogRequest, out *WalletRechargeLogResponse) error
	}
	type WalletRechargeLogService struct {
		walletRechargeLogService
	}
	h := &walletRechargeLogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&WalletRechargeLogService{h}, opts...))
}

type walletRechargeLogServiceHandler struct {
	WalletRechargeLogServiceHandler
}

func (h *walletRechargeLogServiceHandler) Create(ctx context.Context, in *WalletRechargeLog, out *WalletRechargeLogResponse) error {
	return h.WalletRechargeLogServiceHandler.Create(ctx, in, out)
}

func (h *walletRechargeLogServiceHandler) Delete(ctx context.Context, in *WalletRechargeLog, out *WalletRechargeLogResponse) error {
	return h.WalletRechargeLogServiceHandler.Delete(ctx, in, out)
}

func (h *walletRechargeLogServiceHandler) Detail(ctx context.Context, in *WalletRechargeLog, out *WalletRechargeLogResponse) error {
	return h.WalletRechargeLogServiceHandler.Detail(ctx, in, out)
}

func (h *walletRechargeLogServiceHandler) Search(ctx context.Context, in *WalletRechargeLogRequest, out *WalletRechargeLogResponse) error {
	return h.WalletRechargeLogServiceHandler.Search(ctx, in, out)
}
