// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hookService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for HookService service

func NewHookServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for HookService service

type HookService interface {
	//商品接口数据
	GoodsResultHandle(ctx context.Context, in *HookRequest, opts ...client.CallOption) (*GoodsResultResponse, error)
	//下单接口数据
	BuyResultHandle(ctx context.Context, in *HookRequest, opts ...client.CallOption) (*BuyResultResponse, error)
	//购买订单优惠处理
	BuyCalculate(ctx context.Context, in *HookRequest, opts ...client.CallOption) (*BuyCalculateResponse, error)
}

type hookService struct {
	c    client.Client
	name string
}

func NewHookService(name string, c client.Client) HookService {
	return &hookService{
		c:    c,
		name: name,
	}
}

func (c *hookService) GoodsResultHandle(ctx context.Context, in *HookRequest, opts ...client.CallOption) (*GoodsResultResponse, error) {
	req := c.c.NewRequest(c.name, "HookService.GoodsResultHandle", in)
	out := new(GoodsResultResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookService) BuyResultHandle(ctx context.Context, in *HookRequest, opts ...client.CallOption) (*BuyResultResponse, error) {
	req := c.c.NewRequest(c.name, "HookService.BuyResultHandle", in)
	out := new(BuyResultResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookService) BuyCalculate(ctx context.Context, in *HookRequest, opts ...client.CallOption) (*BuyCalculateResponse, error) {
	req := c.c.NewRequest(c.name, "HookService.BuyCalculate", in)
	out := new(BuyCalculateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HookService service

type HookServiceHandler interface {
	//商品接口数据
	GoodsResultHandle(context.Context, *HookRequest, *GoodsResultResponse) error
	//下单接口数据
	BuyResultHandle(context.Context, *HookRequest, *BuyResultResponse) error
	//购买订单优惠处理
	BuyCalculate(context.Context, *HookRequest, *BuyCalculateResponse) error
}

func RegisterHookServiceHandler(s server.Server, hdlr HookServiceHandler, opts ...server.HandlerOption) error {
	type hookService interface {
		GoodsResultHandle(ctx context.Context, in *HookRequest, out *GoodsResultResponse) error
		BuyResultHandle(ctx context.Context, in *HookRequest, out *BuyResultResponse) error
		BuyCalculate(ctx context.Context, in *HookRequest, out *BuyCalculateResponse) error
	}
	type HookService struct {
		hookService
	}
	h := &hookServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&HookService{h}, opts...))
}

type hookServiceHandler struct {
	HookServiceHandler
}

func (h *hookServiceHandler) GoodsResultHandle(ctx context.Context, in *HookRequest, out *GoodsResultResponse) error {
	return h.HookServiceHandler.GoodsResultHandle(ctx, in, out)
}

func (h *hookServiceHandler) BuyResultHandle(ctx context.Context, in *HookRequest, out *BuyResultResponse) error {
	return h.HookServiceHandler.BuyResultHandle(ctx, in, out)
}

func (h *hookServiceHandler) BuyCalculate(ctx context.Context, in *HookRequest, out *BuyCalculateResponse) error {
	return h.HookServiceHandler.BuyCalculate(ctx, in, out)
}
