// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: memberCouponService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MemberCouponService service

func NewMemberCouponServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MemberCouponService service

type MemberCouponService interface {
	//用户优惠券删除
	Delete(ctx context.Context, in *MemberCoupon, opts ...client.CallOption) (*MemberCouponResponse, error)
	//用户优惠劵详情
	Detail(ctx context.Context, in *MemberCoupon, opts ...client.CallOption) (*MemberCouponResponse, error)
	//我的优惠劵
	Index(ctx context.Context, in *MemberCouponRequest, opts ...client.CallOption) (*MemberCouponIndexResponse, error)
	//用户优惠劵查询
	Search(ctx context.Context, in *MemberCouponRequest, opts ...client.CallOption) (*MemberCouponResponse, error)
	//用户优惠劵可用列表（支付展示）
	UsableList(ctx context.Context, in *MemberCouponRequest, opts ...client.CallOption) (*MemberCouponResponse, error)
}

type memberCouponService struct {
	c    client.Client
	name string
}

func NewMemberCouponService(name string, c client.Client) MemberCouponService {
	return &memberCouponService{
		c:    c,
		name: name,
	}
}

func (c *memberCouponService) Delete(ctx context.Context, in *MemberCoupon, opts ...client.CallOption) (*MemberCouponResponse, error) {
	req := c.c.NewRequest(c.name, "MemberCouponService.Delete", in)
	out := new(MemberCouponResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberCouponService) Detail(ctx context.Context, in *MemberCoupon, opts ...client.CallOption) (*MemberCouponResponse, error) {
	req := c.c.NewRequest(c.name, "MemberCouponService.Detail", in)
	out := new(MemberCouponResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberCouponService) Index(ctx context.Context, in *MemberCouponRequest, opts ...client.CallOption) (*MemberCouponIndexResponse, error) {
	req := c.c.NewRequest(c.name, "MemberCouponService.Index", in)
	out := new(MemberCouponIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberCouponService) Search(ctx context.Context, in *MemberCouponRequest, opts ...client.CallOption) (*MemberCouponResponse, error) {
	req := c.c.NewRequest(c.name, "MemberCouponService.Search", in)
	out := new(MemberCouponResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberCouponService) UsableList(ctx context.Context, in *MemberCouponRequest, opts ...client.CallOption) (*MemberCouponResponse, error) {
	req := c.c.NewRequest(c.name, "MemberCouponService.UsableList", in)
	out := new(MemberCouponResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemberCouponService service

type MemberCouponServiceHandler interface {
	//用户优惠券删除
	Delete(context.Context, *MemberCoupon, *MemberCouponResponse) error
	//用户优惠劵详情
	Detail(context.Context, *MemberCoupon, *MemberCouponResponse) error
	//我的优惠劵
	Index(context.Context, *MemberCouponRequest, *MemberCouponIndexResponse) error
	//用户优惠劵查询
	Search(context.Context, *MemberCouponRequest, *MemberCouponResponse) error
	//用户优惠劵可用列表（支付展示）
	UsableList(context.Context, *MemberCouponRequest, *MemberCouponResponse) error
}

func RegisterMemberCouponServiceHandler(s server.Server, hdlr MemberCouponServiceHandler, opts ...server.HandlerOption) error {
	type memberCouponService interface {
		Delete(ctx context.Context, in *MemberCoupon, out *MemberCouponResponse) error
		Detail(ctx context.Context, in *MemberCoupon, out *MemberCouponResponse) error
		Index(ctx context.Context, in *MemberCouponRequest, out *MemberCouponIndexResponse) error
		Search(ctx context.Context, in *MemberCouponRequest, out *MemberCouponResponse) error
		UsableList(ctx context.Context, in *MemberCouponRequest, out *MemberCouponResponse) error
	}
	type MemberCouponService struct {
		memberCouponService
	}
	h := &memberCouponServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MemberCouponService{h}, opts...))
}

type memberCouponServiceHandler struct {
	MemberCouponServiceHandler
}

func (h *memberCouponServiceHandler) Delete(ctx context.Context, in *MemberCoupon, out *MemberCouponResponse) error {
	return h.MemberCouponServiceHandler.Delete(ctx, in, out)
}

func (h *memberCouponServiceHandler) Detail(ctx context.Context, in *MemberCoupon, out *MemberCouponResponse) error {
	return h.MemberCouponServiceHandler.Detail(ctx, in, out)
}

func (h *memberCouponServiceHandler) Index(ctx context.Context, in *MemberCouponRequest, out *MemberCouponIndexResponse) error {
	return h.MemberCouponServiceHandler.Index(ctx, in, out)
}

func (h *memberCouponServiceHandler) Search(ctx context.Context, in *MemberCouponRequest, out *MemberCouponResponse) error {
	return h.MemberCouponServiceHandler.Search(ctx, in, out)
}

func (h *memberCouponServiceHandler) UsableList(ctx context.Context, in *MemberCouponRequest, out *MemberCouponResponse) error {
	return h.MemberCouponServiceHandler.UsableList(ctx, in, out)
}
