// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: traceService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TraceService service

func NewTraceServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TraceService service

type TraceService interface {
	//查询物流信息
	Query(ctx context.Context, in *TraceRequest, opts ...client.CallOption) (*TraceResponse, error)
}

type traceService struct {
	c    client.Client
	name string
}

func NewTraceService(name string, c client.Client) TraceService {
	return &traceService{
		c:    c,
		name: name,
	}
}

func (c *traceService) Query(ctx context.Context, in *TraceRequest, opts ...client.CallOption) (*TraceResponse, error) {
	req := c.c.NewRequest(c.name, "TraceService.Query", in)
	out := new(TraceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TraceService service

type TraceServiceHandler interface {
	//查询物流信息
	Query(context.Context, *TraceRequest, *TraceResponse) error
}

func RegisterTraceServiceHandler(s server.Server, hdlr TraceServiceHandler, opts ...server.HandlerOption) error {
	type traceService interface {
		Query(ctx context.Context, in *TraceRequest, out *TraceResponse) error
	}
	type TraceService struct {
		traceService
	}
	h := &traceServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TraceService{h}, opts...))
}

type traceServiceHandler struct {
	TraceServiceHandler
}

func (h *traceServiceHandler) Query(ctx context.Context, in *TraceRequest, out *TraceResponse) error {
	return h.TraceServiceHandler.Query(ctx, in, out)
}
